on: 
  [workflow_dispatch]

name: azureClusterCreation
jobs:
  buildCluster:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Log in with Azure
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          
    - name: Terraform Install
      env:
        TERRAFORM_VERSION: "1.1.0"
      run: |
          tf_version=$TERRAFORM_VERSION
          wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
          unzip terraform_"$tf_version"_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          
    - name: Terraform version
      run: terraform --version
        
    - name: Terraform Init
      run: |
        az login --service-principal -u ef558906-5fcf-4194-805a-ccb72e91a01d -p l~uXPREqBvu_M8et46Vodp~f_5N0tq0AWO --tenant d5ddcb9e-d608-4dfe-ad5d-f425dc316442
        terraform init -input=false
