on: 
  [workflow_dispatch]
env:
  REGISTRY_NAME: myregistryrishi
  CLUSTER_NAME: cluster-rg-dev-cluster
  CLUSTER_RESOURCE_GROUP: cluster-rg-dev
  NAMESPACE: myns
  APP_NAME: hubapp
  APP_NAME1: nodeapp
  SECRET: acrsecret

jobs:
  storageAccountCreation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend       
    steps:
    - uses: actions/checkout@main
    - name: Log in with Azure
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: Terraform Install
      env:
            TERRAFORM_VERSION: "1.0.1"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        
    - name: Terraform version
      run: terraform --version
        
    - name: Terraform Init
      run: |
        az login
        terraform init -input=false
        terraform plan
        terraform apply --auto-approve -input=false
